# Generated by Django 5.0.9 on 2026-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Masalan: Ism, Manzil', max_length=60, verbose_name='Nomi')),
                ('value', models.CharField(max_length=200, verbose_name='Qiymati')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Men haqimda — qator',
                'verbose_name_plural': 'Men haqimda — qatorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Men haqimda', max_length=100, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name="Qo'shimcha matn")),
            ],
            options={
                'verbose_name': 'Men haqimda — sarlavha',
                'verbose_name_plural': 'Men haqimda — sarlavha',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Keling, birga ishlaymiz!', max_length=100, verbose_name='Sarlavha')),
                ('section_subtitle', models.CharField(blank=True, max_length=200, verbose_name="Qo'shimcha matn")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('show_phone', models.BooleanField(default=False, help_text="Ochiq raqam spam yig'uvchi botlar nishoniga aylanadi.", verbose_name="Telefon saytda ko'rinsin")),
                ('github_username', models.CharField(blank=True, max_length=60, verbose_name='GitHub foydalanuvchi nomi')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub havolasi')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram havolasi')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn havolasi')),
                ('form_name_label', models.CharField(default='Ismingiz', max_length=60, verbose_name='Forma: ism maydoni')),
                ('form_email_label', models.CharField(default='Email', max_length=60, verbose_name='Forma: email maydoni')),
                ('form_message_label', models.CharField(default='Xabar', max_length=60, verbose_name='Forma: xabar maydoni')),
                ('form_button_text', models.CharField(default='Yuborish', max_length=60, verbose_name='Forma: tugma matni')),
                ('form_success_text', models.CharField(default="Xabaringiz yuborildi. Tez orada bog'lanaman.", max_length=200, verbose_name='Forma: muvaffaqiyat matni')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqa',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='AZIZBEK', max_length=60, verbose_name='Kichik yozuv')),
                ('title', models.CharField(default='FULL-STACK DASTURCHI', max_length=120, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(default='Zamonaviy va foydali veb-ilovalarni yaratishga qiziqaman.', verbose_name='Tavsif')),
                ('button_text', models.CharField(default='Loyiha boshlash', max_length=60, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='#projects', max_length=100, verbose_name='Tugma havolasi')),
            ],
            options={
                'verbose_name': 'Hero (bosh ekran)',
                'verbose_name_plural': 'Hero (bosh ekran)',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('sent_to_telegram', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
            ],
            options={
                'verbose_name': 'Kelgan xabar',
                'verbose_name_plural': 'Kelgan xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Nomi')),
                ('anchor', models.CharField(help_text='Masalan: #home, #about, #projects, #contact', max_length=100, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsin")),
                ('is_button', models.BooleanField(default=False, help_text="Oxirgi element uchun belgilang — ko'k tugma bo'lib chiqadi.", verbose_name="Tugma ko'rinishida")),
            ],
            options={
                'verbose_name': 'Menyu elementi',
                'verbose_name_plural': 'Menyu (Nav)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, help_text='Kompyuteringizdan rasm tanlang.', null=True, upload_to='loyihalar/', verbose_name='Rasm')),
                ('live_url', models.URLField(blank=True, help_text="Agar loyiha veb-sayt bo'lsa, manzilini kiriting.", verbose_name='Sayt havolasi')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub havolasi')),
                ('tech_stack', models.CharField(blank=True, help_text='Vergul bilan ajrating: Django, PostgreSQL, JavaScript', max_length=200, verbose_name='Texnologiyalar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_published', models.BooleanField(default=True, verbose_name="Saytda ko'rinsin")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Loyihalarim', max_length=100, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(default='Mening ishlarim va dasturiy yechimlarim', max_length=200, verbose_name="Qo'shimcha matn")),
                ('empty_text', models.CharField(default="Loyihalar tez orada qo'shiladi.", max_length=200, verbose_name="Bo'sh holat matni")),
            ],
            options={
                'verbose_name': 'Loyihalar — sarlavha',
                'verbose_name_plural': 'Loyihalar — sarlavha',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='AZIZBEK', max_length=50, verbose_name='Logo matni')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Profil rasmi')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/', verbose_name='Favicon')),
                ('footer_text', models.CharField(default='Barcha huquqlar himoyalangan.', max_length=200, verbose_name='Footer matni')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV fayli (PDF)')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
