# Generated by Django 5.0.9 on 2026-07-28 17:02

import core.db_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fayl (bazada)',
                'verbose_name_plural': 'Fayllar (bazada)',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(default='FULL-STACK\nDASTURCHI', help_text='Yangi qatorga tushirish uchun Enter bosing.', max_length=120, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Kompyuteringizdan rasm tanlang.', null=True, storage=core.db_storage.DatabaseStorage(), upload_to='loyihalar/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='title',
            field=models.CharField(default='Avvalgi loyihalarim', max_length=100, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=core.db_storage.DatabaseStorage(), upload_to='cv/', verbose_name='CV fayli (PDF)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.db_storage.DatabaseStorage(), upload_to='favicon/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.db_storage.DatabaseStorage(), upload_to='profil/', verbose_name='Profil rasmi'),
        ),
    ]
