# Generated by Django 5.0.9 on 2026-07-28 17:37

import core.db_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dbfile_alter_hero_title_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='show_phone',
            field=models.BooleanField(default=True, help_text="Ochiq raqam spam botlar nishoniga aylanishi mumkin, lekin portfolio uchun odatda ko'rsatiladi.", verbose_name="Telefon saytda ko'rinsin"),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text="Kompyuteringizdan rasm tanlang. O'chirish uchun 'Tozalash' katagini belgilang.", null=True, storage=core.db_storage.DatabaseStorage(), upload_to='loyihalar/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="O'chirish uchun: pastdagi 'Tozalash' katagini belgilab, saqlang.", null=True, storage=core.db_storage.DatabaseStorage(), upload_to='profil/', verbose_name='Profil rasmi'),
        ),
    ]
