# Generated by Django 5.0.9 on 2026-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_show_phone_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='title_gold',
            field=models.CharField(blank=True, default='DASTURCHI', help_text="Ikkinchi qator — oltin rangda. Bo'sh qoldirsangiz, faqat 1-qator chiqadi.", max_length=120, verbose_name='Sarlavha (2-qator, oltin)'),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(default='FULL-STACK', help_text='Birinchi qator — oq rangda.', max_length=120, verbose_name='Sarlavha (1-qator, oq)'),
        ),
    ]
